spring.application.name=soul-app-service
server.port=9090
springdoc.openapi.enabled=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.zdwfjtynazbhueenqbzi
spring.datasource.password=H6oppClqWNX6Spjd
# Optional properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
secret.key=abcdefg1234567890